"""
Issue formatting for GitHub issues from TfSec findings
"""
from datetime import datetime
from typing import Optional
from .models import TfSecFinding


class IssueFormatter:
    """Formats TfSec findings into GitHub issue content"""
    
    @staticmethod
    def format_issue_body(finding: TfSecFinding) -> str:
        """Format a TfSec finding into GitHub issue body markdown"""
        scan_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        # Build the main content table
        content = f"""## Security Finding Details

| Field | Value |
|-------|-------|
| **Rule ID** | {finding.rule_id} |
| **Long ID** | {finding.long_id} |
| **Severity** | **{finding.severity}** |
| **Provider** | {finding.rule_provider.upper()} |
| **Service** | {finding.rule_service} |
| **Resource** | `{finding.resource}` |
| **File** | {finding.location.file_basename} |
| **Lines** | {finding.location.line_range_str} *(from scan time - may have shifted)* |
| **Scan Date** | {scan_date} |

## Description
{finding.description}

## Impact
{finding.impact}

## Resolution
{finding.resolution}

## Technical Details
- **Full Rule Description**: {finding.rule_description}
- **Full File Path**: `{finding.location.filename}`
- **Warning Level**: {"Yes" if finding.warning else "No"}
- **Status Code**: {finding.status}

## Documentation Links"""

        # Add documentation links
        for i, link in enumerate(finding.links, 1):
            content += f"\n{i}. [{link}]({link})"

        # Add footer
        content += f"""

---
*This issue was automatically created by **tfgitsec** from TfSec security scan results.*  
*Line numbers are from scan time and may have shifted due to code changes.*

**Unique ID**: `{finding.unique_id}`
"""

        return content

    @staticmethod
    def format_reopen_comment(scan_date: Optional[str] = None) -> str:
        """Format comment for when reopening a resolved issue"""
        if scan_date is None:
            scan_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
            
        return f"""🔄 **Security Issue Detected Again**

This previously resolved security issue has reappeared in the latest TfSec scan.

- **Scan Date**: {scan_date}
- **Status**: Automatically reopened by tfgitsec

Please review and address this security finding again."""

    @staticmethod
    def format_close_comment(scan_date: Optional[str] = None) -> str:
        """Format comment for when auto-closing a resolved issue"""
        if scan_date is None:
            scan_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
            
        return f"""🎉 **Security Issue Resolved**

This security issue is no longer detected in the latest TfSec security scan.

- **Scan Date**: {scan_date}
- **Status**: Automatically resolved

*This issue was auto-closed by tfgitsec because the security finding no longer appears in the scan results.*"""

    @staticmethod
    def format_summary_comment(stats: dict, scan_date: Optional[str] = None) -> str:
        """Format a summary comment with scan statistics"""
        if scan_date is None:
            scan_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        total = stats.get("total", 0)
        by_severity = stats.get("by_severity", {})
        by_service = stats.get("by_service", {})
        
        content = f"""## 📊 TfSec Security Scan Summary

**Scan Date**: {scan_date}  
**Total Findings**: {total}

### Findings by Severity"""

        if by_severity:
            for severity in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
                count = by_severity.get(severity, 0)
                if count > 0:
                    icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵"}.get(severity, "⚫")
                    content += f"\n- {icon} **{severity}**: {count}"
        else:
            content += "\n- No findings by severity data available"

        content += "\n\n### Findings by AWS Service"
        
        if by_service:
            for service, count in sorted(by_service.items()):
                content += f"\n- **{service}**: {count}"
        else:
            content += "\n- No findings by service data available"

        content += "\n\n---\n*Automated scan summary generated by tfgitsec*"
        
        return content
